DREHMAL_MC_NAME_OVERRIDES = {
	"bedrock": "Condensed Veilstone",
	"wither_rose": "Chthonic Rose",
	"nether_brick_slab": "Taihryte Brick Slab",
	"soul_torch": "Orderflame Torch",
	"respawn_anchor": "Spectra Charge",
	"blue_ice": "Divine Ice",
	"netherrack": "Taihryte",
	"nether_portal": "OFF LIMITS",
	"nether_bricks": "Taihryte Bricks",
    "nether_brick_fence": "Taihryte Brick Fence",
    "nether_brick_stairs": "Taihryte Brick Stairs",
    "nether_wart": "Crucible Wart",
    "warped_wart_block": "Aventurine Pileus Block",
    "warped_stem": "Aventurine Stem",
    "stripped_warped_stem": "Stripped Aventurine Stem",
    "warped_hyphae": "Aventurine Hyphae",
    "stripped_warped_hyphae": "Stripped Aventurine Hyphae",
    "crimson_stem": "Carnelian Stem",
    "stripped_crimson_stem": "Stripped Carnelian Stem",
    "crimson_hyphae": "Carnelian Hyphae",
    "stripped_crimson_hyphae": "Stripped Carnelian Hyphae",
    "warped_nylium": "Aventurine Nylium",
    "crimson_nylium": "Carnelian Nylium",
    "warped_fungus": "Aventurine Fungus",
    "crimson_fungus": "Carnelian Fungus",
    "crimson_roots": "Carnelian Roots",
    "warped_roots": "Aventurine Roots",
    "nether_sprouts": "Aventurine Sprouts",
    "shroomlight": "Flarepod",
    "soul_soil": "Souldust",
	"warped_planks": "Aventurine Planks",
	"warped_slab": "Aventurine Slab",
	"warped_pressure_plate": "Aventurine Pressure Plate",
	"warped_fence": "Aventurine Fence",
	"warped_trapdoor": "Aventurine Trapdoor",
	"warped_fence_gate": "Aventurine Fence Gate",
	"warped_stairs": "Aventurine Stairs",
	"warped_button": "Aventurine Button",
	"warped_door": "Aventurine Door",
	"warped_sign": "Aventurine Sign",
	"warped_hanging_sign": "Aventurine Hanging Sign",
	"warped_wall_sign": "Aventurine Wall Sign",
	"crimson_planks": "Carnelian Planks",
	"crimson_slab": "Carnelian Slab",
	"crimson_pressure_plate": "Carnelian Pressure Plate",
	"crimson_fence": "Carnelian Fence",
	"crimson_trapdoor": "Carnelian Trapdoor",
	"crimson_fence_gate": "Carnelian Fence Gate",
	"crimson_stairs": "Carnelian Stairs",
	"crimson_button": "Carnelian Button",
	"crimson_door": "Carnelian Door",
	"crimson_sign": "Carnelian Sign",
	"crimson_wall_sign": "Carnelian Wall Sign",
	"crimson_hanging_sign": "Carnelian Hanging Sign",
	"soul_fire": "Orderflame",
    "enchanting_table": "Runic Inscription Table",
	"end_stone": "Otherstone",
	"end_portal_frame": "Anomaly Inhibitor",
	"dragon_egg": "Fear's Husk",
	"ender_chest": "Primal Cache",
	"emerald_ore": "Fossilized Serpent Scale",
	"deepslate_emerald_ore": "Slate Fossilized Serpent Scale",
	"emerald_block": "Block of Serpent Scales",
	"beacon": "Asterial Array",
	"sea_lantern": "Azure Lantern",
	"end_rod": "Light Rod",
	"purpur_block": "Amethyst Tile Block",
	"purpur_pillar": "Infused Amethyst",
	"purpur_stairs": "Amethyst Tile Stairs",
	"purpur_slab": "Amethyst Tile Slab",
	"end_stone_bricks": "Otherstone Bricks",
	"nether_wart_block": "Crucible Wart Block",
	"red_nether_bricks": "Red Taihryte Bricks",
	"shulker_box": "Runic Vessel",
	"white_shulker_box": "White Runic Vessel",
	"orange_shulker_box": "Orange Runic Vessel",
	"magenta_shulker_box": "Magenta Runic Vessel",
	"light_blue_shulker_box": "Light Blue Runic Vessel",
	"yellow_shulker_box": "Yellow Runic Vessel",
	"lime_shulker_box": "Lime Runic Vessel",
	"pink_shulker_box": "Pink Runic Vessel",
	"gray_shulker_box": "Gray Runic Vessel",
	"light_gray_shulker_box": "Light Gray Runic Vessel",
	"cyan_shulker_box": "Cyan Runic Vessel",
	"purple_shulker_box": "Purple Runic Vessel",
	"blue_shulker_box": "Blue Runic Vessel",
	"brown_shulker_box": "Brown Runic Vessel",
	"green_shulker_box": "Green Runic Vessel",
	"red_shulker_box": "Red Runic Vessel",
	"black_shulker_box": "Black Runic Vessel",
	"end_portal": "Anomaly",
	"potted_wither_rose": "Potted Chthonic Rose",
	"wither_skeleton_wall_skull": "Chthonic Skeleton Wall Skull",
	"wither_skeleton_skull": "Chthonic Skeleton Skull",
	"dragon_head": "Head of Tethlaen",
	"end_gateway": "Void Gateway",
	"structure_void": "Structure Void",
	"structure_block": "Minecraft Sex Block",
	"bubble_column": "bubbles!!",
	"conduit": "Aqua Fortis",
	"jigsaw": "Eldermead Bottle",
	"end_stone_brick_stairs": "Otherstone Brick Stairs",
	"red_nether_brick_stairs": "Red Taihryte Brick Stairs",
	"end_stone_brick_slab": "Otherstone Brick Slab",
	"red_nether_brick_slab": "Red Taihryte Brick Slab",
	"nether_brick_wall": "Taihryte Brick Wall",
	"red_nether_brick_wall": "Red Taihryte Brick Wall",
	"end_stone_brick_wall": "Otherstone Brick Wall",
	"soul_lantern": "Orderflame Lantern",
	"soul_campfire": "Orderflame Campfire",
	"netherite_block": "Block of Celestial Alloy",
	"ancient_debris": "Celestial Debris",
	"crying_obsidian": "Silent Obsidian",
	"cracked_nether_bricks": "Cracked Taihryte Bricks",
	"chiseled_nether_bricks": "Chiseled Taihryte Bricks",
    # Items
	"spectral_arrow": "Truesight Arrow",
	"emerald": "Scale",
	"enchanted_golden_apple": "Fruit of the Primal Tree",
	"ender_pearl": "Primal Pearl",
	"ghast_tear": "Quicksilver Tear",
	"nether_wart": "Crucible Wart",
	"end_crystal": "Unstable Primal Catalyst",
	"ender_eye": "Oculus of Nothing",
	"bat_spawn_egg": "Masayoshi",
	"bee_spawn_egg": "Peace Treaty",
	"blaze_spawn_egg": "Inert Mythbreaker",
	"cat_spawn_egg": "Crystal Digging Claws",
	"cave_spider_spawn_egg": "Cave Spider Spawn Egg",
	"chicken_spawn_egg": "Flammer",
	"cod_spawn_egg": "Syzygy",
	"cow_spawn_egg": "Calamity",
	"creeper_spawn_egg": "Parenchyma",
	"dolphin_spawn_egg": "Zenith",
	"donkey_spawn_egg": "Avsohm'Kohl",
	"drowned_spawn_egg": "Drowned Spawn Egg",
	"elder_guardian_spawn_egg": "Elder Dahrkin Spawn Egg",
	"enderman_spawn_egg": "Penumbra",
	"endermite_spawn_egg": "Osteogenesis",
	"evoker_spawn_egg": "Thundercrux",
	"ghast_spawn_egg": "Pure Corruption",
	"glow_squid_spawn_egg": "Eyebiter",
	"guardian_spawn_egg": "Proxigea",
	"hoglin_spawn_egg": "Swinebreed Spawn Egg",
	"horse_spawn_egg": "Rehntite Plate Mail",
	"ravager_spawn_egg": "AvPod",
	"llama_spawn_egg": "Ascendance",
	"magma_cube_spawn_egg": "The Mythbreaker",
	"ocelot_spawn_egg": "Frenzy",
	"panda_spawn_egg": "Tul'Vohaln",
	"parrot_spawn_egg": "One Thousand Scars",
	"pig_spawn_egg": "Malevolentia",
	"piglin_spawn_egg": "Maelmari Spawn Egg",
	"piglin_brute_spawn_egg": "Maelmari Brute Spawn Egg",
	"pillager_spawn_egg": "Mihkmari Spawn Egg",
	"phantom_spawn_egg": "Whispersong",
	"pufferfish_spawn_egg": "Hovadchear's Greathammer",
	"rabbit_spawn_egg": "Ultva's Bowblade",
	"fox_spawn_egg": "Stasis Bolt",
	"salmon_spawn_egg": "Magestep",
	"sheep_spawn_egg": "Oblivion",
	"silverfish_spawn_egg": "Voidtear Dagger",
	"squid_spawn_egg": "The Frostfang",
	"strider_spawn_egg": "Laikin Spawn Egg",
	"trader_llama_spawn_egg": "Orchidaceae",
	"tropical_fish_spawn_egg": "Festering Strides",
	"turtle_spawn_egg": "Eldermead Bottle",
	"vex_spawn_egg": "Emperor Anyr's Scepter",
	"wandering_trader_spawn_egg": "Aurastaff of Permafrost",
	"vindicator_spawn_egg": "Mihkmari Warrior Spawn Egg",
	"witch_spawn_egg": "Aeongale",
	"wither_skeleton_spawn_egg": "Chthonic Skeleton Spawn Egg",
	"wolf_spawn_egg": "The Heartaxe",
	"zoglin_spawn_egg": "Zwinebreed Spawn Egg",
	"zombie_spawn_egg": "Eldermead",
	"zombified_piglin_spawn_egg": "Necrotic Maelmari Spawn Egg",
	"zombie_villager_spawn_egg": "WarpHorse Receiver MkII",
	"goat_spawn_egg": "WarpHorse Armor MkIII",
	"experience_bottle": "Arcane Bottle",
	"nether_star": "Soul Asteria",
	"nether_brick": "Taihryte Brick",
	"prismarine_crystals": "Azure Crystals",
	"elytra": "Glider",
	"shulker_shell": "Null Shell",
	"phantom_membrane": "Ruin Membrane",
	"heart_of_the_sea": "Moonstone",
	"netherite_upgrade": "Celestial Upgrade",
	"netherite_scrap": "Celestial Chondrule",
	"netherite_ingot": "Celestial Alloy",
	"netherite_helmet": "Celestial Helmet",
	"netherite_chestplate": "Celestial Chestplate",
	"netherite_leggings": "Celestial Leggings",
	"netherite_boots": "Celestial Boots",
	"netherite_axe": "Celestial Axe",
	"netherite_pickaxe": "Celestial Pickaxe",
	"netherite_hoe": "Celestial Hoe",
	"netherite_shovel": "Celestial Shovel",
	"netherite_sword": "Celestial Sword",
	"warped_fungus_on_a_stick": "Aventurine Fungus on a Stick",
    # Entities
	"cave_spider": "Arahk",
	"elder_guardian": "Dahrkin Negator",
	"end_crystal": "Unstable Primal Catalyst",
	"ender_dragon": "Tethlaen, Lost to Nothing",
	"ender_pearl": "Thrown Primal Pearl",
	"enderman": "Primal Walker",
	"endermite": "Null Pest",
	"evoker_fangs": "Mihkmari Arcanist Fangs",
	"evoker": "Mihkmari Arcanist",
	"eye_of_ender": "Oculus of Nothing",
	"ghast": "Charbelcher",
	"guardian": "Dahrkin",
	"hoglin": "Swinebreed",
	"ravager": "Grafted Mihkmari",
	"killer_bunny": "Heartbreaker Bunny",
	"phantom": "Skullchild",
	"piglin": "Maelmari",
	"piglin_brute": "Maelmari Brute",
	"pillager": "Mihkmari",
	"polar_bear": "Faehrbear",
	"shulker": "Null Clam",
	"shulker_bullet": "Null Clam Bullet",
	"spectral_arrow": "Truesight Arrow",
	"strider": "Laikin",
	"iron_golem": "Runic Golem",
	"vindicator": "Mihkmari Warrior",
	"witch": "Forsaken Alchemist",
	"wither": "The Soulgrafted",
	"wither_skeleton": "Chthonic Skeleton",
	"wither_skull": "Chthonic Skull",
	"zoglin": "Zwinebreed",
	"zombified_piglin": "Necrotic Maelmari",
}